language: python

matrix:
  include:
  - python: "pypy"
  - python: "pypy3"
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
install:
  - pip install coveralls tox
  - python setup.py bdist_wheel
  - "pip install --only-binary=:all: ./dist/vulture-*.whl"
script:
  - python --version
  - vulture vulture/ tests/
  - python -m vulture vulture/ tests/
  - tox -e py
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then tox -e style; fi
after_success:
  - coveralls
