version: 1.0.{build}

# Do not build feature branches that are already built as part of a pull request.
skip_branch_with_pr: true

environment:
  matrix:
  - TOXENV: py27
    PYTHON: C:\Python27-x64\python.exe
  - TOXENV: py35
    PYTHON: C:\Python35-x64\python.exe
  - TOXENV: py36
    PYTHON: C:\Python36-x64\python.exe
  - TOXENV: py37
    PYTHON: C:\Python37-x64\python.exe

install:
- cmd: "%PYTHON% -m pip install -U pip setuptools tox virtualenv wheel"

build_script:
- cmd: "%PYTHON% setup.py bdist_wheel"
- cmd: "%PYTHON% -m pip install --only-binary=:all: --no-index --ignore-installed --find-links=dist/ vulture"

test_script:
- cmd: "%PYTHON% --version"
- cmd: "%PYTHON% -m vulture vulture/ tests/"
- cmd: "%PYTHON% -m tox -e py"

matrix:
  fast_finish: false
